# this is a simple test device setup that's used to compile and test the examples
esphome:
  name: components_test
  build_path: build/components_test

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

external_components:
  - source:
      type: git
      url: https://github.com/mhetzi/esphome_vdmot.git
    components: [ vdmot ]
    refresh: always

