# this configuration file has all empty components set up.
# use 'esphome compile test_empty_components.yaml' to build.

packages:
  device: !include device.yaml  # include our test device setup

globals:
  - id: overlay_percentage
    type: float
    restore_value: no
    initial_value: '0'
  - id: climate_percentage
    type: float
    restore_value: no
    initial_value: '0'

i2c:
  sda: 22
  scl: 23
  scan: True
  id: bus_a
  frequency: 50kHz

output:
  - platform: template
    id: mixingOutput
    type: float
    power_supply: vorlauf_pumpe
    write_action:
      - lambda: |-
            id(climate_percentage) = state;
            float level = state - id(overlay_percentage);
            //ESP_LOGD("mixingOutput", "IMPLEMENT SET LEVEL TO VALVE");
            auto call = id(valve_1).make_call();
            call.set_position(level);
            call.perform();
  - platform: gpio
    pin: 17
    id: 'test_out'
    power_supply: vorlauf_pumpe

  - platform: gpio
    pin: 13
    id: 'pin_valve_open'
    inverted: false
  - platform: gpio
    pin: 14
    id: 'pin_valve_close'

text_sensor:
  - platform: template
    name: "Temperature Quelle"
    id: "temp_source"

one_wire:
  - platform: gpio
    pin: 21

vdmot:
  ina219_id: ina_component
  output_close_id: pin_valve_close
  output_open_id: pin_valve_open
  ina219_current_id: ina_current
  max_motor_current: 0.06
  id: vdmot_hubb
  valve:
    name: Fußbodenheizung Ventil
    id: valve_1
  calibrate:
    name: "Kalibriere Ventil"
  maintenance:
    name: "Wartung durchführen"

sensor:
  - platform: ina219
    address: 0x40
    id: ina_component
    shunt_resistance: 0.1 ohm
    current:
      name: "INA219 Current"
      id: ina_current
      filters:
        - delta: 0.00050
    max_voltage: 3.3V
    max_current: 0.4A
    update_interval: 10s
  - platform: dallas_temp
    address: 0x4D03173058DCFF28
    name: "Vorlauf Temperatur"
    update_interval: 15s
    id: vorlauf_temp
    on_value:
      then:
        - lambda: |-
            #define in_min 45.0f
            #define in_max 55.5f
            #define out_min 0.0f
            #define out_max 1.0f
            // map  function
            float f =  (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
            id(overlay_percentage) = f < 0.0f ? 0.0f : f;
            id(mixingOutput).set_level( id(climate_percentage) );
    filters:
      - delta: 0.2
      - lambda: |-
          if (x < 0.00 || x > 100)
            return {};
          return x;

#  Vorlauf Pumpe nur einschlaten wenn wir den Fußboden heizen wollen
power_supply:
  - id: 'vorlauf_pumpe'
    pin:
      number: 16  #  16 is real pin
      inverted: False
      mode: OUTPUT
    enable_time: 1s
    keep_on_time: 2s
